= Empezando
include::{partialsdir}/attributes-es.adoc[]
:xlist-release: 0.0.1

A continuación veremos un pequeño tutorial en el que instalaremos un pequeño sistema de listas negras en un servidor GNU/Linux. El objetivo de este tutorial es familiarizar al usuario con las herramientas y mostrar una pequeña parte de lo que nos ofrece el software, si desea ver su uso en algún escenario "real" puede ver alguna de las guías disponibles.

== Instalando y probando

Usaremos el instalador del paquete, para ello simplemente copiaremos y pegaremos el siguiente contenido en una shell.

[source,bash]
[subs="attributes"]
----
RELEASE="{xlist-release}"
DOWNLOAD_BASE="https://github.com/luids-io/xlist/releases/download"
DOWNLOAD_URI="$DOWNLOAD_BASE/v$RELEASE/installer_linux.sh"
wget $DOWNLOAD_URI -O installer_xlist.sh
chmod 755 installer_xlist.sh
sudo ./installer_xlist.sh -u
----

El instalador instala unos scripts `systemd` para la inicialización de los servicios, pero no los inicia ni activa, esto debe hacerlo explícitamente el administrador de sistemas. Para ello lo inicializaremos con `systemctl`.

[source,bash]
----
systemctl start luids-xlistd
----

Podemos ver que está funcionando, utilizando el comando `xlistc`.
----
$ xlistc
[ip4 ip6 domain] (1.972164ms)
----

== Nuestra primera lista negra

En una instalación estándar, la configuración del servicio `xlistd` se realiza en el fichero `/etc/luids/xlist/xlistd.toml`. Dentro de dicho fichero se hace referencia a la definición del servicio que, en la instalación estándar, se encuentra en el fichero `/etc/luids/xlist/services.json`.

.Contenido de `/etc/luids/xlist/services.json`
[source,json]
----
[
    {
        "id": "root",
        "class": "wbefore",
        "resources": [ "ip4", "ip6", "domain" ],
        "contains": [
            {
                "id": "local-whitelist",
                "class": "file",
                "resources": [ "ip4", "ip6", "domain" ],
                "source": "local/whitelist.xlist",
                "opts": {
                    "autoreload": true,
                    "reloadseconds": 5
                }
            },
            {
                "id": "local-blacklist",
                "class": "file",
                "resources": [ "ip4", "ip6", "domain" ],
                "source": "local/blacklist.xlist",
                "opts": {
                    "autoreload": true,
                    "reloadseconds": 5,
                    "reason": "found in 'local-blacklist'"
                }
            }
        ]
    }
]
----

Podemos observar que en dicho fichero se hace referencia a unos ficheros de listas locales. Dichos ficheros se encuentran en `/var/lib/luids/xlist/local`. Modificaremos los ficheros con el siguiente contenido.

.Contenido de `/var/lib/luids/xlist/local/blacklist.xlist`
[source]
----
ip4,plain,1.2.3.4
ip4,cidr,10.0.0.0/8
domain,plain,www.badsite.com
domain,sub,malware.com
----

.Contenido de `/var/lib/luids/xlist/local/whitelist.xlist`
[source]
----
domain,plain,bueno.malware.com
----

Esperaremos unos segundos y probaremos nuestro sistema de listas negras recién configurado...
----
$ xlistc
[ip4 ip6 domain] (1.248051ms)
$ xlistc 1.2.3.4 10.2.1.54 1.2.3.5
ip4,1.2.3.4: true,"found in 'local-blacklist'",0 (728.003µs)
ip4,10.2.1.54: true,"found in 'local-blacklist'",0 (763.039µs)
ip4,1.2.3.5: false,"",0 (695.131µs)
$ xlistc www.badsite.com any.malware.com bueno.malware.com www.google.com
domain,www.badsite.com: true,"found in 'local-blacklist'",0 (248.943µs)
domain,any.malware.com: true,"found in 'local-blacklist'",0 (333.688µs)
domain,bueno.malware.com: false,"",0 (251.833µs)
domain,www.google.com: false,"",0 (417.03µs)
----

== Siguientes pasos

En este tutorial hemos visto la construcción de un sencillo sistema de listas negras, pero no hemos entrado a entender el detalle de su configuración ni en la utilización de fuentes de datos externas. Tampoco hemos visto muchas de las funcionalidades que el software *xlist* nos ofrece como el uso de listas en zonas _DNS_, geolocalización, listas blancas, puntuaciones... Todo eso se verá en los siguientes capítulos.

ifdef::env-site,env-github[]
A continuación: xref:installation.adoc[Instalación]
endif::env-site,env-github[]
