= Introducción
include::{partialsdir}/attributes-es.adoc[]
:guidename: advanced-dns-sinkhole

== Qué es ^lu^IDS

include::{partialsdir}/what-luids.adoc[]

== Qué es un sumidero DNS o DNS Sinkhole

include::{partialsdir}/what-dns-sinkhole.adoc[]

== ¿Qué tiene de especial nuestro sumidero?

Como probablemente conozca el lector, ya existe diverso software capaz de realizar esta labor, sin embargo la mayoría no es libre y el que es libre (como el popular _BIND_ o el nuevo _PiHole_), usa un planteamiento distinto y, a nuestro juicio, menos versátil.

La particularidad de nuestro sumidero es que, como se verá en los diagramas de secuencia de la siguiente sección, involucra diferentes componentes: por un lado tenemos un _servidor DNS_ (basado en el popular _CoreDNS_) que realiza las tareas típicas de resolución y, por otro lado, tenemos un _servidor xlist_ que se encarga de la tarea de comprobar la existencia en las listas. Junto a estos servidores, tenemos dos servicios "auxiliares" más: un _servidor de archivo_ que se encargará de almacenar la información y un _servidor de eventos_ que se encargará de procesar los eventos que se generen. Esta separación de responsabilidades nos permitirá, además de una alta especialización de cada software en su correspondiente rol, implementar sistemas más robustos y escalables.

El resumen de las funcionalidades que tendrá el sumidero que desarrollaremos en esta guía será el siguiente:

* Chequeará los nombres de dominio a resolver en diferentes listas negras y, dependiendo del caso, chequeará además los CNAMEs y direcciones IP devueltas.
* Responderá en función de las políticas aplicadas a cada tipo de lista negra, pudiendo devolver desde un "dominio no existente" a una determinada IP.
* Generará eventos de distinto nivel en función de la lista a la que pertenezca.
* Archivará las resoluciones DNS que se realicen en una base de datos MongoDB.
* Archivará los eventos que se generen en una base de datos MongoDB.
* Podremos acceder al archivo mediante una interfaz de administración web.

ifdef::env-site,env-github[]
A continuación: xref:design.adoc[Diseño del sistema]
endif::env-site,env-github[]
