= Configuración
include::{partialsdir}/attributes-es.adoc[]
:guidename: basic-nfqueue-xlist

include::{partialsdir}/download-xlist-database.adoc[leveloffset=1]

== Configuración de xlget

En primer lugar hay que configurar los orígenes de las listas negras definidas, para ello copiaremos de la base de datos xlist los ficheros de definición de `feeds` en `/etc/luids/xlist/sources.d`.

[source,bash]
----
mkdir -p /etc/luids/xlist/sources.d
cd /etc/luids/xlist/sources.d
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/sources/abuse-ch.json .
ln -s $DBDIR/sources/alienvault-com.json .
ln -s $DBDIR/sources/badips-com.json .
ln -s $DBDIR/sources/blocklist-de.json .
ln -s $DBDIR/sources/blocklist-site.json .
ln -s $DBDIR/sources/cinsscore-com.json .
ln -s $DBDIR/sources/cruzit-com.json .
ln -s $DBDIR/sources/cymru-com.json .
ln -s $DBDIR/sources/darklist-de.json .
ln -s $DBDIR/sources/dataplane-org.json .
ln -s $DBDIR/sources/dshield-org.json .
ln -s $DBDIR/sources/emergingthreats-net.json .
ln -s $DBDIR/sources/greensnow-co.json .
ln -s $DBDIR/sources/interserver-net.json .
ln -s $DBDIR/sources/myip-ms.json .
ln -s $DBDIR/sources/rutgers-edu.json .
ln -s $DBDIR/sources/spamhaus-org.json .
ln -s $DBDIR/sources/talosintelligence-com.json .
ln -s $DBDIR/sources/turris-cz.json .
----

Editaremos los ficheros `json` recién copiados y sustituiremos `"disabled": true` por `false` en la definición de las listas enumeradas en el apartado anterior.

Editaremos el fichero de configuración de `xlget` para incluir el directorio como fuentes.

.Contenido de `/etc/luids/xlist/xlget.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlget.toml[]
----

Una vez creados dichos ficheros podemos chequear su correcta sintaxis mediante el comando `xlget_check`.
----
$ sudo xlget_check
INFO[0000] xlget (version: adf9e50 build: 2020-09-10T06:39:57+0200)
configuration ok
needs update: 'abuse.ch-feodo' 'abuse.ch-ssl' 'alienvault.com' 'badips.com' 'blocklist.de' 'blocklist.site-malware' 'cinsscore.com' 'cruzit.com' 'cymru.com-fullbogons4' 'darklist.de' 'dataplane.org-sshpwauth' 'dshield.org' 'emergingthreats.net' 'greensnow.co' 'interserver.net' 'myip.ms-full' 'rutgers.edu' 'spamhaus.org-drop' 'talosintelligence.com' 'turris.cz'
----

Tras la validación, vamos a realizar la descarga de las listas. Para ello utilizaremos el comando `xlget_update`.
----
$ sudo xlget_update
INFO[0000] xlget (version: adf9e50 build: 2020-09-10T06:39:57+0200)
INFO[0000] getting 'abuse.ch-feodo'
INFO[0000] summary 'abuse.ch-feodo': updated=true ip4=840 ip6=0 domain=0 md5=0 sha1=0 sha256=0
...
INFO[0034] getting 'talosintelligence.com'
INFO[0036] summary 'talosintelligence.com': updated=true ip4=838 ip6=0 domain=0 md5=0 sha1=0 sha256=0
INFO[0036] getting 'turris.cz'
INFO[0037] summary 'turris.cz': updated=true ip4=24249 ip6=12 domain=0 md5=0 sha1=0 sha256=0
INFO[0037] xlget finished
----

En la salida se mostrarán algunos _warnings_ (que podremos ignorar) y el número de elementos que se han extraído de cada una de las listas. Podemos ver que las listas se han descargado correctamente en el directorio `/var/lib/luids/xlist`.

Para despreocuparnos completamente de la actualización de las listas, inicializaremos el servicio `xlget` para que chequee automáticamente y actualice las listas si es necesario. Además lo habilitaremos para que se inicie con el sistema.

[source,bash]
----
sudo systemctl start luids-xlget
sudo systemctl enable luids-xlget
----

== Configuración de xlistd

La configuración de `xlistd` se divide en dos partes:

* Definición del servicio.
* Parámetros de configuración del servidor.

La definición del servicio la realizaremos utilizando múltiples ficheros para que se entienda mejor. Deberemos crear los siguientes ficheros con su correspondiente contenido.

[source,bash]
----
cd /usr/local/share/xlist-database/database
sudo mkdir -p /etc/luids/xlist/services.d/high
sudo cp file/alienvault-com.json /etc/luids/xlist/services.d/high
sudo cp file/cymru-com.json /etc/luids/xlist/services.d/high
sudo cp file/interserver-net.json /etc/luids/xlist/services.d/high
sudo cp file/spamhaus-org.json /etc/luids/xlist/services.d/high
sudo cp file/talosintelligence-com.json /etc/luids/xlist/services.d/high
----

[source,bash]
----
cd /usr/local/share/xlist-database/database
sudo mkdir -p /etc/luids/xlist/services.d/low
sudo cp file/abuse-ch.json /etc/luids/xlist/services.d/low
sudo cp file/badips-com.json /etc/luids/xlist/services.d/low
sudo cp file/blocklist-de.json /etc/luids/xlist/services.d/low
sudo cp file/blocklist-site.json /etc/luids/xlist/services.d/low
sudo cp file/cinsscore-com.json /etc/luids/xlist/services.d/low
sudo cp file/cruzit-com.json /etc/luids/xlist/services.d/low
sudo cp file/darklist-de.json /etc/luids/xlist/services.d/low
sudo cp file/dataplane-org.json /etc/luids/xlist/services.d/low
sudo cp file/dshield-org.json /etc/luids/xlist/services.d/low
sudo cp file/emergingthreats-net.json /etc/luids/xlist/services.d/low
sudo cp file/greensnow-co.json /etc/luids/xlist/services.d/low
sudo cp file/myip-ms.json /etc/luids/xlist/services.d/low
sudo cp file/rutgers-edu.json /etc/luids/xlist/services.d/low
sudo cp file/turris-cz.json /etc/luids/xlist/services.d/low
----

[source,bash]
----
mkdir -p /etc/luids/xlist/services.d/files
cd /etc/luids/xlist/services.d/files
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/services/files/blocklist-site-abuse.json .
ln -s $DBDIR/services/files/blocklist-site-ads.json .
ln -s $DBDIR/services/files/blocklist-site-crypto.json .
ln -s $DBDIR/services/files/blocklist-site-malware.json .
ln -s $DBDIR/services/files/blocklist-site-phishing.json .
ln -s $DBDIR/services/files/blocklist-site-ransomware.json .
ln -s $DBDIR/services/files/blocklist-site-scam.json .
ln -s $DBDIR/services/files/blocklist-site-tracking.json .
----

Editaremos los ficheros `json` recién copiados y sustituiremos `"disabled": true` por `false` en la definición de las listas enumeradas en el apartado <<design-sources>>. También editaremos la configuración relativa a las listas `abuse.ch-ssl` y `blocklist.site-malware`, dejando únicamente el recurso `ip4` para ahorrar memoria.


.Contenido de `/etc/luids/xlist/services.d/low/foreign-countries.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/low/foreign-countries.json[]
----

.Contenido de `/etc/luids/xlist/services.d/high-confidence.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/high-confidence.json[]
----

.Contenido de `/etc/luids/xlist/services.d/low-confidence.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/low-confidence.json[]
----

.Contenido de `/etc/luids/xlist/services.d/custom-local.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/custom-local.json[]
----

.Contenido de `/etc/luids/xlist/service.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.json[]
----

Nótese que también es necesario descargar la base de datos de _geoip2_. A partir de Enero de 2020 ya no está accesible de forma abierta y es necesario descargar manualmente (previo registro) desde https://dev.maxmind.com/geoip/geoip2/geolite2/. Hay que descargar el _tar.gz_ de `GeoLite2 Country` en formato _mmdb_. Una vez descargado descomprimirlo y copiarlo al directorio de datos de xlist.
----
$ tar zxvf GeoLite2-Country_20200915.tar.gz
GeoLite2-Country_20200915/
GeoLite2-Country_20200915/COPYRIGHT.txt
GeoLite2-Country_20200915/GeoLite2-Country.mmdb
GeoLite2-Country_20200915/LICENSE.txt
$ sudo cp GeoLite2-Country_20200915/GeoLite2-Country.mmdb /var/lib/luids/xlist/
----

Ahora creamos el fichero de configuración del servidor.

.Contenido de `/etc/luids/xlist/xlistd.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlistd.toml[]
----

Comprobaremos que la configuración es correcta, como se muestra a continuación.
----
# xlistd --config /etc/luids/xlist/xlistd.toml --dry-run
INFO[0000] xlistd (version: adf9e50 build: 2020-09-10T06:39:54+0200)
configuration seems ok
----

Inicializaremos y habilitaremos el servicio `xlistd`.

.Inicializa servicio `xlistd` y habilita al inicio
[source,bash]
----
sudo systemctl start luids-xlistd
sudo systemctl enable luids-xlistd
----

Tras unos segundos, podremos probar el correcto funcionamiento del servidor utilizando el comando `xlistc` para hacerle consultas.
----
$ xlistc
[ip4] (1.361466ms)
$ xlistc 8.8.8.8
ip4,8.8.8.8: false,"",0 (381.32µs)
----

Ya que lo tenemos correctamente funcionando, "publicaremos" (de forma local) el servicio de listas negras que hemos creado para que esté disponible para el resto de servicios. Esto lo haremos editando el fichero `/etc/luids/apiservices.json`

.Contenido de `/etc/luids/apiservices.json`
[source,json]
----
include::{examplesdir}/etc/luids/apiservices.json[]
----

== Configuración de lunfqueue

La configuración nuevamente se divide en configuración del servidor y definición del servicio.

.Contenido de `/etc/luids/netfilter/lunfqueue.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/netfilter/lunfqueue.toml[]
----

IMPORTANT: Deberás reemplazar la dirección de red `192.168.0.0/24` por la de tu red local.

El servicio se configurará mediante la definición de los plugins y acciones que se van a aplicar. Esto se realizará mediante el siguiente fichero de configuración.

.Contenido de `/etc/luids/netfilter/plugins-nfqueue.json`
[source,json]
----
include::{examplesdir}/etc/luids/netfilter/plugins-nfqueue.json[]
----

Comprobaremos que la configuración es correcta.
----
# lunfqueue --config /etc/luids/netfilter/lunfqueue.toml --dry-run
INFO[0000] lunfqueue (version: f096c19 build: 2020-09-10T06:45:40+0200)
configuration seems ok
----

Una vez probado, inicializaremos y habilitaremos el servicio

[source,bash]
----
sudo systemctl start luids-lunfqueue
sudo systemctl enable luids-lunfqueue
----

== Prueba de configuración de Netfilter

Ya tenemos el componente _lunfqueue_ respondiendo a las peticiones de la cola netfilter con identificador `100`. Lo siguiente es establecer las reglas del cortafuegos en las cuales se realizará la comprobación. Sin embargo, antes de hacerlo puede ser conveniente probar que el sistema funciona correctamente. Para ello puede probar agregando la siguiente regla de prueba:

[source,bash]
----
sudo iptables -I OUTPUT -p icmp -j NFQUEUE --queue-num 100
----

De esta forma, para cualquier ping que se lance se realizará la comprobación. Podemos ver que funciona correctamente procediendo de la forma que se muestra a continuación.
----
$ ping -c 3 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=63 time=14.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=63 time=15.9 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=63 time=15.7 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2004ms
rtt min/avg/max/mdev = 14.704/15.420/15.905/0.516 ms
$ sudo head -1 /var/lib/luids/xlist/alienvault.com.xlist
ip4,plain,2.81.219.150
$ ping -c 3 2.81.219.150
PING 2.81.219.150 (2.81.219.150) 56(84) bytes of data.

--- 2.81.219.150 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2045ms

$ sudo tail -5 /var/log/syslog
Sep 17 07:51:15 luids-router lunfqueue[2381]: time="2020-09-17T07:51:15+02:00" level=info msg="starting netfilter queue processing service"
Sep 17 07:51:15 luids-router lunfqueue[2381]: time="2020-09-17T07:51:15+02:00" level=info msg="starting nfqueue #100"
Sep 17 07:53:19 luids-router lunfqueue[2381]: time="2020-09-17T07:53:19+02:00" level=info msg="ip-processor.checkip: 10.0.2.15->2.81.219.150 2.81.219.150 {Result:true Reason:found in 'alienvault.com' TTL:0}"
Sep 17 07:53:20 luids-router lunfqueue[2381]: time="2020-09-17T07:53:20+02:00" level=info msg="ip-processor.checkip: 10.0.2.15->2.81.219.150 2.81.219.150 {Result:true Reason:found in 'alienvault.com' TTL:0}"
Sep 17 07:53:21 luids-router lunfqueue[2381]: time="2020-09-17T07:53:21+02:00" level=info msg="ip-processor.checkip: 10.0.2.15->2.81.219.150 2.81.219.150 {Result:true Reason:found in 'alienvault.com' TTL:0}"
----

Una vez testeado, eliminaremos la regla recién creada para las pruebas.

[source,bash]
----
sudo iptables -D OUTPUT -p icmp -j NFQUEUE --queue-num 100
----

== Consolidación del firewall

Ahora que hemos comprobado que el sistema funciona correctamente sólo falta agregar a nuestro cortafuegos las reglas que necesitamos. Una posible regla que chequease las nuevas conexiones a nuestro servidor web podrían ser las siguientes:

[source,bash]
----
iptables -A INPUT -p tcp --match multiport --dport 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --match multiport --dport 80,443 -m conntrack --ctstate NEW -j NFQUEUE --queue-num 100
iptables -A OUTPUT -p tcp --match multiport --sport 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
----

WARNING: A pesar de que el sistema ofrece bajas latencias, el chequeo debería limitarse a las nuevas conexiones. Puede leer más recomendaciones en
xref:netfilter:netfilter-integration.adoc[Integración con Netfilter].

ifdef::env-site,env-github[]
A continuación: xref:next-steps.adoc[Siguientes pasos]
endif::env-site,env-github[]
