ifdef::env-site,env-github[= Guía: Servidor DNS con zona RBL para servicio Antispam]
:guidename: basic-dns-rblzone
include::{partialsdir}/attributes-es.adoc[]
//ifdef::env-site,env-github[:toc:]

En la siguiente guía vamos a ver cómo configurar *un servidor DNS con una zona que ofrezca servicio de lista negra de acuerdo al RFC5782*, posteriormente esta zona será consumida por un servicio de correo para admitir o denegar conexiones SMTP entrantes de direcciones conocidas de Spam. Para "crear" esta lista utilizaremos varios servicios ya disponibles en Internet que ofrecen su información también mediante una zona DNS.

TIP: No solamente los servicios de correo pueden hacer uso de una zona RBL, también otros sistemas como algunos cortafuegos pueden hacer uso de esta configuración.

NOTE: A pesar de la extensión de esta guía, puedes realizar la configuración de esta guía *en menos de 5 minutos* únicamente con la información de los apartados de <<installation>> y <<configuration>>. Además tienes a tu disposición todos los ficheros de configuración de esta guía https://github.com/luids-io/docs/blob/master/es/modules/guides/examples/basic-dns-rblzone[aquí].

[[introduction]]
== Introducción

=== ¿Por qué esta configuración?

Una tarea común en los sistemas de correo es comprobar si el servidor que trata de entregar un email para uno de sus destinatarios se encuentra en una lista negra. Para ello, generalmente suelen configurarse los controles en dos fases: la primera fase la realiza el MTA, es decir, el propio software de servidor de correo (por ejemplo _Postfix_). Este chequeo incluye diversas comprobaciones genéricas: si IP tiene resolución inversa, si hay registro SPF, si se hace greylisting, etc.  Además se suelen poner varias zonas DNSxL con información de listas negras. Tras estas comprobaciones, el email pasará a la siguiente fase, en la que otra herramienta más especializada (como puede ser _SpamAssasin_) aplicará diversos filtros más intensivos en recursos (estadísticos, etc) así como cálculos de puntuaciones utilizando un número mayor de lista negras, etc.

En general, suele ser recomendable el uso de listas negras en la primera fase para evitar el consumo de recursos innecesario de la segunda. Sin embargo, las opciones que presenta el MTA para esto suelen ser reducidas.  En el caso de _Postfix_, hasta la llegada de las opciones de chequeo `postscreen` (que se producen antes de que se de cualquier conversación SMTP) y que admite el uso de _thresholds_ (umbrales de respuesta), ni siquiera permitían sistemas de puntuaciones.

=== ¿Qué tiene de especial nuestro sistema?

A pesar de las opciones que pueda ofrecernos un sistema como _Postfix_, nunca va a proveer las funcionalidades que puede proporcionar en este aspecto un _servidor XList_: puntuaciones, chequeos en listas locales y sincronización para consulta "offline", geolocalización, tasas de consulta, gestión de fallos, métricas por lista, estadísticas, etc.

Por todo ello, esta es la propuesta para la presente guía: configurar un servidor _xlistd_ con las listas que utilice nuestro sistema antispam y proporcionarlas mediante un servidor _ludns_ con el plugin _xlistrbl_ que sirva una zona para las consultas del servidor de correo. De esta forma únicamente habrá que configurar una zona en el MTA y el sistema _xlistd_ se encargará del resto. Nótese lo oportuno de esta configuración si tenemos una granja de servidores MTA.

image::why-antispam.svg[why-antispam,width=80%,pdfwidth=80%]

Una posible secuencia de chequeo del sistema sería:

.*Secuencia de chequeo positivo*
[plantuml,{guidename}-sequence, png,pdfwidth=100%]
....
actor "MAIL Server\n(postfix)" as postfix
participant "DNS Server\n(ludns)" as ludns
participant "XList Server\n(xlistd)" as xlistd
participant "External 1\nDNS Server" as extdns1 #99FF99
participant "External 2\nDNS Server" as extdns2 #99FF99
participant "External N\nDNS Server" as extdnsN #99FF99

postfix -> ludns: query 44.33.22.11.rbl.mizone.net
ludns -> xlistd: Check(11.22.33.44)

xlistd -> extdns1: query 44.33.22.11.rbl.extdns1.net
xlistd -> extdns2: query 44.33.22.11.rbl.extdns2.net
xlistd -> extdnsN: query 44.33.22.11.rbl.extdnsN.net
extdns1 --> xlistd: nxdomain
extdns2 --> xlistd: 127.0.0.10
extdnsN --> xlistd: 127.0.0.2

xlistd -> ludns: {result: true, reason: "spam"}
ludns -> postfix: 127.0.0.69

postfix -> ludns: TXT 44.33.22.11.rbl.mizone.net
ludns -> ludns: CACHED
ludns -> postfix: "spam"
....


Esta guía se trata de una configuración básica así que no se verán todas las funcionalidades que ofrece nuestro sistema. Sin embargo, conviene que el usuario las conozca por si se anima a continuar explorando más allá de esta guía. Algunas de las funcionalidades adicionales son:

* ofrece soporte de nombres de dominio e ipv6,
* es posible usar listas negras online y sincronizarlas,
* es posible alojar múltiples zonas utilizando a su vez diferentes servidores _xlistd_,
* es posible reutilizar las listas y dar servicio a múltiples servidores _DNS_,
* provee de instrumentación para su integración en un sistema de monitorización _Prometheus_ y así tener información en "tiempo real",
* disponible en _Docker_ y con algunas características que lo hace ideal para su despliegue en entornos Cloud con herramientas como _Kubernetes_.

Así que una vez visto qué es y qué ventajas aporta nuestro software sobre otros, pongámonos manos a la obra.

[[design]]
== Diseño del sistema

[[design-sources]]
=== Selección de los orígenes

En primer lugar vamos a seleccionar los orígenes que vamos a utilizar. Un buen sitio por donde empezar es https://github.com/luids-io/xlist-database[la base de datos XList].

Para esta configuración me baso en esta configuración recomendada para un sistema Antispam:
http://know.mailsbestfriend.com/papers/SmarterMail-Antispam-Settings.shtml

Por motivos de brevedad, usaremos la siguiente configuración correspondiente al _SMTP Blocking_:

----
NOTE*** We do realize that only one weight can be specified per test. Since
this is the case, we suggest that you use weight 10 for all of the tests below
(use weight 30 for GBUDB) if you are going to use them for both Filtering and
Incoming SMTP Blocking

BARRACUDA – weight of 10

ANY/ALL SORBS – weight of 10

SPAMCOP – weight of 10

ZEN – weight of 10

GBUDB – weight of 30

HOSTKARMA-BLACK – weight of 10

MAILSPIKE – weight of 10

MCAFEE – weight of 10

SURRIEL – weight of 10
----

Las listas que usaremos serán:

* `barracudacentra.org`
* `gbudb.net`
* `junkemailfilter.com`
* `mailspike.net`
* `mcafee.com`
* `sorbs.net`
* `spamcop.net`
* `spamhaus.org`
* `surriel.com`

Además de estos orígenes externos, también daremos a nuestro sistema cierta flexibilidad, incorporando nuestras propias listas blancas y negras.

[[design-service]]
=== Diseño del servicio de listas

Nuestro servicio de listas utilizará en primer lugar una lista blanca y posteriormente buscará en las listas negras de la siguiente forma:

.Funcionamiento básico de nuestro sistema
[plantuml,{guidename}-flow-basic, png,pdfwidth=80%]
----
start
:read ip4/
if (my-whitelist.check(ip4)?) then (true)
	:result = false|
else (false)
	if (my-blacklist.check(ip4)?) then (true)
		:result = true|
	else (false)
		if (remote-blacklists.check(ip4)?) then (true)
			:result = true|
		else (false)
			:result = false|
		endif
	endif
endif
stop
----

En el caso de las listas remotas además de implementar un sistema de caché, utilizaremos un sistema de puntuación, que se comportará de la siguiente forma:

.Chequeo en listas remotas
[plantuml,{guidename}-flow-remote,png,pdfwidth=30%]
----
start
:read ip4/
:score = 0|
repeat
	:next = remote-blacklists.Next()|
	if (next.check(ip4)?) then (true)
		:score = score +next.Score()|
	endif
repeat while (remote-blacklists.HasNext()?)

if (score > 20) then (true)
	:result = true|
else (false)
	:result = false|
endif
stop
----


El servicio de listas negras lo modelaremos utilizando algunos de los componentes que ofrece el sistema _xlistd_. Una representación gráfica de dicha definición podría ser la siguiente:

.Diseño del servicio _xlistd_ para la lista antispam
image::{guidename}-design.svg[design,width=85%,pdfwidth=100%]


[[design-components]]
=== Despliegue de los componentes

Como vamos a desplegar el software sobre un único sistema, el diagrama de despliegue quedará de la siguiente forma:

.*Diagrama de despliegue*
[plantuml,{guidename}-deployment,png,pdfwidth=70%]
....
cloud "Blacklists" {
 [DNS server] -down- ExtDNS
}

node "DNS RBL" {
  [xlistd] --> ExtDNS
  [xlistd] - GRPC
  [ludns] --> GRPC
  [ludns] - DNS
}

node "Mail Server" {
  [Postfix] --> DNS
  [SpamAssasin] --> DNS
}
....

NOTE: En esta guía únicamente desplegaremos los componentes `xlistd` y `ludns` vistos en el diagrama.

[[installation]]
== Instalación

WARNING: Este proceso está probado únicamente en un sistema _Ubuntu 20.04LTS_ server. Los binarios están compilados estáticamente y las rutas empleadas son las de una distribución estándar, por lo que el instalador debería funcionar en cualquier distribución. Si necesita más información o quiere instalarlo sobre otras plataformas puede consultar los xref:manuals:index.adoc[manuales de las
herramientas].

IMPORTANT: Recuerde que si prefiere usar `docker` también puede desplegar el escenario de esta guía https://github.com/luids-io/deploy/docker/basic-dns-rblzone[usando docker compose].

include::{partialsdir}/install-xlist.adoc[leveloffset=2]

include::{partialsdir}/install-dns.adoc[leveloffset=2]

[[configuration]]
== Configuración

IMPORTANT: Puede descargar los ficheros de configuración de esta guía https://github.com/luids-io/docs/blob/master/es/modules/guides/examples/basic-dns-rblzone[aquí].

=== Descarga de base de datos xlist

La manera más sencilla de obtener la base de datos es con un `git clone` o descargando la última release. Podremos dejar la base de datos

[source,bash]
----
git clone https://github.com/luids-io/xlist-database
sudo mv xlist-database /usr/local/share
----

=== Configuración de xlistd

La configuración de `xlistd` se divide en dos partes:

* Definición del servicio.
* Parámetros de configuración del servidor.

La definición del servicio la realizaremos utilizando múltiples ficheros para que se entienda mejor. Deberemos crear los siguientes ficheros con su correspondiente contenido.

[source,bash]
----
cd /usr/local/share/xlist-database/database
sudo mkdir -p /etc/luids/xlist/services.d/remote
sudo cp dnsxl/barracudacentral-org.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/gbudb-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/junkemailfilter-com.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/mailspike-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/mcafee-com.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/sorbs-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/spamcop-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/spamhaus-org.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/psbl-surriel-com.json /etc/luids/xlist/services.d/remote
----

Editaremos los ficheros `json` recién copiados y sustituiremos `"disabled": true` por `false` en la definición de las listas enumeradas en el apartado <<design-sources>>.

Crearemos los siguientes archivos.

.Contenido de `/etc/luids/xlist/service.d/remote.json`
[source,json]
----
include::{examplesdir}/{guidename}/etc/luids/xlist/service.d/remote.json[]
----

.Contenido de `/etc/luids/xlist/service.d/custom-local.json`
[source,json]
----
include::{examplesdir}/{guidename}/etc/luids/xlist/service.d/custom-local.json[]
----

.Contenido de `/etc/luids/xlist/service.json`
[source,json]
----
include::{examplesdir}/{guidename}/etc/luids/xlist/service.json[]
----

Para esta configuración, es necesario crear los ficheros `my-blacklist.xlist` y `my-whitelist.xlist` a los que se hacen referencia en `custom-local.json` mediante los siguientes comandos.

[source,bash]
----
sudo touch /var/lib/luids/xlist/my-blacklist.xlist
sudo touch /var/lib/luids/xlist/my-whitelist.xlist
----

Ahora creamos el fichero de configuración del servidor.

.Contenido de `/etc/luids/xlist/xlistd.toml`
[source,toml]
----
include::{examplesdir}/{guidename}/etc/luids/xlist/xlistd.toml[]
----

Comprobaremos que la configuración es correcta, como se muestra a continuación.

[source,console]
----
# xlistd --config /etc/luids/xlist/xlistd.toml --dry-run
INFO[0000] xlistd (version: 341fe0e build: 2020-08-17T07:25:30+0200)
configuration seems ok
----

Inicializaremos y habilitaremos el servicio `xlistd`.

.Inicializa servicio `xlistd` y habilita al inicio
[source,bash]
----
sudo systemctl start luids-xlistd
sudo systemctl enable luids-xlistd
----

Podremos probar el correcto funcionamiento del servidor utilizando el comando `xlistc` para hacerle consultas.

[source,console]
----
$ xlistc
[ip4] (609.687µs)
$ xlistc 8.8.8.8
ip4,8.8.8.8: false,"",0 (1.429557ms)
----

=== Configuración de ludns

La configuración del servidor _DNS_ la realizaremos en dos fases. En la primera fase lo pondremos a escuchar en el puerto no estándar `1053` para hacer pruebas y comprobar que funciona correctamente. En la segunda fase, que se verá en el apartado siguiente, haremos los pasos necesarios para ponerlo a escuchar en el puerto estándar.

La configuración es muy sencilla, basta crear el siguiente fichero:

.Contenido temporal `/etc/ludns/Corefile`
[source]
----
dnsbl.my-domain.lan:1053 {
  idsapi
  xlistrbl
}

.:1053 {
  forward . 8.8.8.8 8.8.4.4
}
----

Una vez creado, hay que iniciar el servidor.

[source,bash]
----
## inicializo ludns
systemctl start ludns
----

Ahora vamos a llevar a cabo las pruebas del servicio utilizando para ello el comando `dig`.

[source,console]
----
# dig @localhost +short -p 1053 2.0.0.127.dnsbl.my-domain.lan //<1>
127.0.0.69
# dig @localhost +short -p 1053 1.0.0.127.dnsbl.my-domain.lan
# dig @localhost +short -p 1053 www.google.com //<2>
216.58.211.36
----
<1> interrogamos a la lista usando una dirección que debería encontrar
<2> interrogamos al servidor local en puerto `1053` por el dominio `www.google.com` y obtenemos respuesta, lo que indica que el servidor asume el rol de resolvedor.


=== Consolidación servicio DNS

Ya tenemos un servidor _DNS_ funcionando pero en un puerto no estándar, así que debemos cambiarlo al puerto que le corresponde. Sin embargo, aquí puede surgir un pequeño problema: puede existir un servidor DNS ya corriendo en dicho puerto.

Esto se debe a que muchas distribuciones optan por poner un pequeño servidor DNS funcionando por defecto para resolver las peticiones locales. Los más habituales son `systemd-resolved` y `dnsmasqd`.

Esta guía está realizada sobre un _Ubuntu 20.04_, por lo que desactivaremos `systemd-resolved` con los siguientes comandos.

[source,bash]
----
## deshabilito systemd-resolved
systemctl disable systemd-resolved.service
systemctl stop systemd-resolved.service

## borro symlink
rm -f /etc/resolv.conf

## creo nuevo resolv.conf que use el servidor dns local
cat >/etc/resolv.conf <<EOF
nameserver 127.0.0.1
options edns0
EOF
----

Ahora modificaremos la configuración de nuestro servidor DNS con la configuración definitiva.

.Contenido de `/etc/ludns/Corefile`
[source]
----
dnsbl.my-domain.lan {
  idsapi
  xlistrbl
}

. {
  forward . 8.8.8.8 8.8.4.4
}
----

IMPORTANT: Si sólo queremos que responda a la zona y no como resolvedor, deberemos eliminar las tres últimas líneas del fichero `Corefile` del ejemplo.

Inicializaremos y habilitaremos el servicio.

[source,bash]
----
## inicio y habilito servicio ludns
systemctl start ludns.service
systemctl enable ludns.service
----

¡Ya tenemos configurado nuestro servidor DNS con la zona antispam!.

=== Configuración del servidor de correo

En primer lugar, el servidor de correo debería ser capaz de resolver la zona creada. Para ello habría dos opciones:

. Usar como resolvedor al servidor DNS recién configurado.
. Configurar la zona padre `my-domain.lan` y delegar la subzona `dnsbl.my-domain.lan` al servidor DNS recién configurado.

IMPORTANT: Conviene proteger con un cortafuegos al servidor DNS para evitar su uso por parte de terceros.

Una vez que el cliente DNS de nuestro servidor de correo está configurado y es capaz de resolver la zona, tan sólo hay que usarla de acuerdo a la configuración.
En el caso de _Postfix_ podría contener algo parecido a esto:

.Posible parte de la configuración de `/etc/postfix/master.cf`
[source]
----
smtpd_recipient_restrictions =
    ....
        reject_rbl_client dnsbl.my-domain.lan,
    ....
----
