[xlist]
datadir = "/var/lib/luids/xlist"

[xlist.service]
dirs       = [ "/etc/luids/xlist/services.d/file",
               "/etc/luids/xlist/services.d" ]
files      = [ "/etc/luids/xlist/service.json" ]
