= Configuración del sistema de listas
include::{partialsdir}/attributes-es.adoc[]
:guidename: basic-dns-sinkhole

En esta sección realizaremos el despliegue de nuestro sistema de listas. Para ello instalaremos el software necesario, configuraremos los orígenes de forma que se actualicen automáticamente y definiremos la relación entre dichos orígenes junto a la lógica a nuestro servicio.

ifdef::env-site,env-github[]
TIP: Recuerde que tiene a su disposición todos los ficheros de configuración de esta guía en https://github.com/luids-io/docs/blob/master/es/modules/guide-{guidename}/examples/.

WARNING: Este proceso está probado únicamente en un sistema _Ubuntu 20.04LTS_ server. Los binarios están compilados estáticamente y las rutas empleadas son las de una distribución estándar, por lo que el instalador debería funcionar en cualquier distribución.
endif::env-site,env-github[]

== Instalación del paquete xlist

include::{partialsdir}/install-xlist.adoc[]

== Descarga de la base de datos xlist

include::{partialsdir}/download-xlist-database.adoc[]

== Configuración de xlget

Tras descargar la base de datos, es necesario en primer lugar configurar los orígenes de las listas que vamos a utilizar. para ello lo mejor es realizar enlaces simbólicos en `/etc/luids/xlist/sources.d`. De este modo, si un origen cambiase de url, formato, etc, nuestro sistema estará actualizado gracias a tener sincronizada la _base de datos xlist_.

Como administradores, ejecutaremos la siguiente secuencia de comandos.

[source,bash]
----
mkdir -p /etc/luids/xlist/sources.d
cd /etc/luids/xlist/sources.d
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/sources/blocklist-site-abuse.json .
ln -s $DBDIR/sources/blocklist-site-ads.json .
ln -s $DBDIR/sources/blocklist-site-crypto.json .
ln -s $DBDIR/sources/blocklist-site-malware.json .
ln -s $DBDIR/sources/blocklist-site-phishing.json .
ln -s $DBDIR/sources/blocklist-site-ransomware.json .
ln -s $DBDIR/sources/blocklist-site-scam.json .
ln -s $DBDIR/sources/blocklist-site-tracking.json .
----

Editaremos el fichero de configuración de `xlget` para incluir el directorio como fuentes.

.Contenido de `/etc/luids/xlist/xlget.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlget.toml[]
----

Una vez creados dichos ficheros podemos chequear su correcta sintaxis mediante el comando `xlget_check` y posteriormente actualizar el contenido de las listas mediante el comando `xlget_update`.
----
# xlget_update
INFO[0000] xlget (version: 341fe0e build: 2020-08-17T07:25:36+0200)
INFO[0000] getting 'blocklist.site-abuse'
INFO[0000] summary 'blocklist.site-abuse': updated=true ip4=0 ip6=0 domain=1220 md5=0 sha1=0 sha256=0
....
INFO[0081] xlget finished
----

NOTE: En la salida pueden mostrarse algunos _warnings_ que podremos ignorar si son de formato.

Tras finalizar el proceso, podemos ver que las listas se han descargado correctamente en el directorio `/var/lib/luids/xlist` también podemos ver en el directorio `/var/lib/luids/xlist/status` información adicional sobre el estado de actualización del contenido de las listas.

Para despreocuparnos completamente de la actualización del contenido de las listas, inicializaremos el servicio `xlget` para que chequee automáticamente y actualice las listas si es necesario. Además lo habilitaremos para que se inicie con el sistema.

[source,bash]
----
sudo systemctl start luids-xlget
sudo systemctl enable luids-xlget
----

== Configuración de xlistd

La configuración de `xlistd` se divide en dos partes:

* Definición del servicio.
* Parámetros de configuración del servidor.

La definición del servicio la realizaremos utilizando múltiples ficheros para que se entienda mejor. Empezaremos por realizar enlaces simbólicos a las listas que vamos a utilizar, para lo que ejecutaremos como administrador la siguiente secuencia de comandos.

[source,bash]
----
mkdir -p /etc/luids/xlist/services.d/file
cd /etc/luids/xlist/services.d/file
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/services/file/blocklist-site-abuse.json .
ln -s $DBDIR/services/file/blocklist-site-ads.json .
ln -s $DBDIR/services/file/blocklist-site-crypto.json .
ln -s $DBDIR/services/file/blocklist-site-malware.json .
ln -s $DBDIR/services/file/blocklist-site-phishing.json .
ln -s $DBDIR/services/file/blocklist-site-ransomware.json .
ln -s $DBDIR/services/file/blocklist-site-scam.json .
ln -s $DBDIR/services/file/blocklist-site-tracking.json .
----

Crearemos un fichero `custom-local.json` que contendrá la definición de nuestra listas negras locales.

.Contenido de `/etc/luids/xlist/services.d/custom-local.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/custom-local.json[]
----

Crearemos un fichero `blocklist-site.json` que incluirá una secuencia de las listas incluidas.

.Contenido de `/etc/luids/xlist/services.d/blocklist-site.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/blocklist-site.json[]
----

Finalmente crearemos el componente raíz en el fichero `service.json` que dará forma a nuestro servicio de agregación.

.Contenido de `/etc/luids/xlist/service.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.json[]
----

Editaremos el fichero de configuración del servidor `xlistd` para que utilice nuestra nueva definición de servicio.

.Contenido de `/etc/luids/xlist/xlistd.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlistd.toml[]
----

Comprobaremos que la configuración es correcta con el siguiente comando.
[source,bash]
----
xlistd --config /etc/luids/xlist/xlistd.toml --dry-run
----

Inicializaremos y habilitaremos el servicio `xlistd`.
[source,bash]
----
sudo systemctl start luids-xlistd
sudo systemctl enable luids-xlistd
----

Podremos probar el correcto funcionamiento del servidor utilizando el comando `xlistc` para hacerle consultas.
----
$ xlistc
[domain] (2.666639ms)
$ xlistc www.google.com
domain,www.google.com: false,"",0 (603.587µs)
----

== Publicación del servicio de listas

Para que el resto de componentes del ecosistema _^lu^IDS_ puedan utilizar nuestro servicio de listas, debemos "publicarlo" en el _registro de servicios de la API_. Esto lo haremos editando el fichero `/etc/luids/apiservices.json`

.Contenido de `/etc/luids/apiservices.json`
[source,json]
----
include::{examplesdir}/etc/luids/apiservices.json[]
----

ifdef::env-site,env-github[]
A continuación: xref:dns-config.adoc[Configuración del servicio dns]
endif::env-site,env-github[]
