[[wrapper-logger]]
= logger
include::{partialsdir}/attributes-es.adoc[]
ifdef::env-site,env-github[:toc:]

== Resumen

=== Descripción

El envoltorio *logger* registra las peticiones del componente.

=== Configuración

* El valor de `class` debe de ser `logger`.
* Admite campos opcionales en `opts`.

[[logger-table-opts]]
[cols="1,1,2"]
.Campos opcionales de _logger_
|===
| Opción | Tipo de dato | Explicación

| `showpeer`
| _boolean_
| muestra el cliente que realiza la consulta

| `found`
| _string_ (disable,debug,info,warn,error)
| cuando la lista da positivo

| `notfound`
| _string_ (disable,debug,info,warn,error)
| cuando la lista da negativo

| `error`
| _string_ (disable,debug,info,warn,error)
| cuando ocurre un error

|===

Por defecto: `found` = "info" y `error` = "warn".

== Ejemplos de uso

=== Uso básico

[[logger-example1]]
.Ejemplo de _logger_
[source,json]
----
include::{examplesdir}/wrappers/logger/example1.json[]
----

Ahora veremos en el log del demonio _xlistd_ las consultas realizadas que retornan un resultado positivo.

[source,console]
----
$ xlistd --xlist.dbfiles example1.json --xlist.rootid="logger1"
INFO[0000] starting xlistd (version: v0.0.1-alpha3 build: 2019-07-10T18:03:04+0200)
INFO[0000] starting registered services
INFO[0000] starting grpc server 127.0.0.1:5801
INFO[0007] logger1: check('1.1.1.1',ip4) = positive (logger1 response)
INFO[0088] logger1: check('1.1.1.2',ip4) = positive (logger1 response)
INFO[0093] logger1: check('1.1.1.3',ip4) = positive (logger1 response)
----

=== Uso avanzado

Si queremos cambiar las opciones por defecto, podemos hacerlo como se muestra en el ejemplo siguiente.

[[logger-example2]]
.Ejemplo de _logger_ personalizado
[source,json]
----
include::{examplesdir}/wrappers/logger/example2.json[]
----
