[nfqueue]
localnets  = [ "127.0.0.0/8", "192.168.250.0/24", "10.0.0.0/8" ]
qids       = [ 100 ]
#onerror = "drop"

[nfqueue.plugin]
files  = [ "/etc/luids/netfilter/plugins-nfqueue.json" ]

[ids.api]
files     = [ "/etc/luids/apiservices.json" ]
