= Configuración
include::{partialsdir}/attributes-es.adoc[]
:guidename: basic-dns-sinkhole

include::{partialsdir}/download-xlist-database.adoc[leveloffset=1]

== Configuración de xlistd

La configuración de `xlistd` se divide en dos partes:

* Definición del servicio.
* Parámetros de configuración del servidor.

La definición del servicio la realizaremos utilizando múltiples ficheros para que se entienda mejor. Deberemos crear los siguientes ficheros con su correspondiente contenido.

[source,bash]
----
cd /usr/local/share/xlist-database/database
sudo mkdir -p /etc/luids/xlist/services.d/remote
sudo cp dnsxl/barracudacentral-org.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/gbudb-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/junkemailfilter-com.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/mailspike-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/mcafee-com.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/sorbs-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/spamcop-net.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/spamhaus-org.json /etc/luids/xlist/services.d/remote
sudo cp dnsxl/psbl-surriel-com.json /etc/luids/xlist/services.d/remote

mkdir -p /etc/luids/xlist/services.d/dnsxl
cd /etc/luids/xlist/services.d/dnsxl
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/services/dnsxl/barracudacentral-org.json .
ln -s $DBDIR/services/dnsxl/gbudb-net.json .
----

Crearemos los siguientes archivos.

.Contenido de `/etc/luids/xlist/service.d/remote.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.d/remote.json[]
----

.Contenido de `/etc/luids/xlist/service.d/custom-local.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.d/custom-local.json[]
----

.Contenido de `/etc/luids/xlist/service.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.json[]
----

Ahora creamos el fichero de configuración del servidor.

.Contenido de `/etc/luids/xlist/xlistd.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlistd.toml[]
----

Comprobaremos que la configuración es correcta, como se muestra a continuación.

[source,console]
----
# xlistd --config /etc/luids/xlist/xlistd.toml --dry-run
INFO[0000] xlistd (version: 341fe0e build: 2020-08-17T07:25:30+0200)
configuration seems ok
----

Inicializaremos y habilitaremos el servicio `xlistd`.

.Inicializa servicio `xlistd` y habilita al inicio
[source,bash]
----
sudo systemctl start luids-xlistd
sudo systemctl enable luids-xlistd
----

Podremos probar el correcto funcionamiento del servidor utilizando el comando `xlistc` para hacerle consultas.
----
$ xlistc
[ip4] (609.687µs)
$ xlistc 8.8.8.8
ip4,8.8.8.8: false,"",0 (1.429557ms)
----

== Configuración de ludns

La configuración del servidor _DNS_ la realizaremos en dos fases. En la primera fase lo pondremos a escuchar en el puerto no estándar `1053` para hacer pruebas y comprobar que funciona correctamente. En la segunda fase, que se verá en el apartado siguiente, haremos los pasos necesarios para ponerlo a escuchar en el puerto estándar.

La configuración es muy sencilla, basta crear el siguiente fichero:

.Contenido temporal `/etc/ludns/Corefile`
[source]
----
dnsbl.my-domain.lan:1053 {
  idsapi
  xlistrbl
}

.:1053 {
  forward . 8.8.8.8 8.8.4.4
}
----

Una vez creado, hay que iniciar el servidor.

[source,bash]
----
## inicializo ludns
systemctl start ludns
----

Ahora vamos a llevar a cabo las pruebas del servicio utilizando para ello el comando `dig`.

----
# dig @localhost +short -p 1053 2.0.0.127.dnsbl.my-domain.lan //<1>
127.0.0.69
# dig @localhost +short -p 1053 1.0.0.127.dnsbl.my-domain.lan
# dig @localhost +short -p 1053 www.google.com //<2>
216.58.211.36
----
<1> interrogamos a la lista usando una dirección que debería encontrar
<2> interrogamos al servidor local en puerto `1053` por el dominio `www.google.com` y obtenemos respuesta, lo que indica que el servidor asume el rol de resolvedor.

== Consolidación servicio DNS

Ya tenemos un servidor _DNS_ funcionando pero en un puerto no estándar, así que debemos cambiarlo al puerto que le corresponde. Sin embargo, aquí puede surgir un pequeño problema: puede existir un servidor DNS ya corriendo en dicho puerto.

Esto se debe a que muchas distribuciones optan por poner un pequeño servidor DNS funcionando por defecto para resolver las peticiones locales. Los más habituales son `systemd-resolved` y `dnsmasqd`.

Esta guía está realizada sobre un _Ubuntu 20.04_, por lo que desactivaremos `systemd-resolved` con los siguientes comandos.

[source,bash]
----
## deshabilito systemd-resolved
systemctl disable systemd-resolved.service
systemctl stop systemd-resolved.service

## borro symlink
rm -f /etc/resolv.conf

## creo nuevo resolv.conf que use el servidor dns local
cat >/etc/resolv.conf <<EOF
nameserver 127.0.0.1
options edns0
EOF
----

Ahora modificaremos la configuración de nuestro servidor DNS con la configuración definitiva.

.Contenido de `/etc/ludns/Corefile`
[source]
----
dnsbl.my-domain.lan {
  idsapi
  xlistrbl
}

. {
  forward . 8.8.8.8 8.8.4.4
}
----

IMPORTANT: Si sólo queremos que responda a la zona y no como resolvedor, deberemos eliminar las tres últimas líneas del fichero `Corefile` del ejemplo.

Inicializaremos y habilitaremos el servicio.

[source,bash]
----
sudo systemctl start luids-ludns.service
sudo systemctl enable luids-ludns.service
----

¡Ya tenemos configurado nuestro servidor DNS con la zona antispam!.

== Configuración del servidor de correo

En primer lugar, el servidor de correo debería ser capaz de resolver la zona creada. Para ello habría dos opciones:

. Usar como resolvedor al servidor DNS recién configurado.
. Configurar la zona padre `my-domain.lan` y delegar la subzona `dnsbl.my-domain.lan` al servidor DNS recién configurado.

IMPORTANT: Conviene proteger con un cortafuegos al servidor DNS para evitar su uso por parte de terceros.

Una vez que el cliente DNS de nuestro servidor de correo está configurado y es capaz de resolver la zona, tan sólo hay que usarla de acuerdo a la configuración.
En el caso de _Postfix_ podría contener algo parecido a esto:

.Posible parte de la configuración de `/etc/postfix/master.cf`
[source]
----
smtpd_recipient_restrictions =
    ....
        reject_rbl_client dnsbl.my-domain.lan,
    ....
----

ifdef::env-site,env-github[]
A continuación: xref:next-steps.adoc[Siguientes pasos]
endif::env-site,env-github[]
