= Configuración
include::{partialsdir}/attributes-es.adoc[]
:guidename: basic-dns-sinkhole

TIP: Tiene a su disposición todos los ficheros de configuración de esta guía en https://github.com/luids-io/docs/blob/master/es/modules/guide-{guidename}/examples/.

== Descarga de la base de datos xlist

include::{partialsdir}/download-xlist-database.adoc[]

== Configuración de xlistd

La configuración de `xlistd` se divide en dos partes:

* Definición del servicio.
* Parámetros de configuración del servidor.

La definición del servicio la realizaremos utilizando múltiples ficheros para que se entienda mejor. Pero antes, deberemos "importar" los servicios remotos que vamos a utilizar usando para ello enlaces simbólicos. Para hacerlo, bastará ejecutar como administrador los siguientes comandos.

[source,bash]
----
mkdir -p /etc/luids/xlist/services.d/dnsxl
cd /etc/luids/xlist/services.d/dnsxl
DBDIR=/usr/local/share/xlist-database
ln -s $DBDIR/services/dnsxl/barracudacentral-org.json .
ln -s $DBDIR/services/dnsxl/gbudb-net.json .
ln -s $DBDIR/services/dnsxl/junkemailfilter-com-black.json .
ln -s $DBDIR/services/dnsxl/mailspike-net-bl.json .
ln -s $DBDIR/services/dnsxl/mcafee-com.json .
ln -s $DBDIR/services/dnsxl/sorbs-net-dul.json .
ln -s $DBDIR/services/dnsxl/sorbs-net-recent.json .
ln -s $DBDIR/services/dnsxl/sorbs-net-new.json .
ln -s $DBDIR/services/dnsxl/spamcop-net.json .
ln -s $DBDIR/services/dnsxl/spamhaus-org-zen.json .
ln -s $DBDIR/services/dnsxl/surriel-com-psbl.json .
----

Crearemos los siguientes archivos.

.Contenido de `/etc/luids/xlist/services.d/remote.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/remote.json[]
----

.Contenido de `/etc/luids/xlist/services.d/custom-local.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/services.d/custom-local.json[]
----

.Contenido de `/etc/luids/xlist/service.json`
[source,json]
----
include::{examplesdir}/etc/luids/xlist/service.json[]
----

Ahora creamos el fichero de configuración del servidor.

.Contenido de `/etc/luids/xlist/xlistd.toml`
[source,toml]
----
include::{examplesdir}/etc/luids/xlist/xlistd.toml[]
----

Comprobaremos que la configuración es correcta, como se muestra a continuación.
----
# xlistd --config /etc/luids/xlist/xlistd.toml --dry-run
INFO[0000] xlistd (version: 341fe0e build: 2020-08-17T07:25:30+0200)
configuration seems ok
----

Inicializaremos y habilitaremos el servicio `xlistd`.

.Inicializa servicio `xlistd` y habilita al inicio
[source,bash]
----
sudo systemctl start luids-xlistd
sudo systemctl enable luids-xlistd
----

Podremos probar el correcto funcionamiento del servidor utilizando el comando `xlistc` para hacerle consultas.
----
$ xlistc
[ip4] (609.687µs)
$ xlistc 8.8.8.8
ip4,8.8.8.8: false,"",0 (1.429557ms)
----

== Registro del servicio xlist

Para que el resto de componentes del ecosistema _^lu^IDS_ puedan utilizar nuestro servicio de listas, debemos "publicarlo" en el _registro de servicios de la API_. Esto lo haremos editando el fichero `/etc/luids/apiservices.json`

.Contenido de `/etc/luids/apiservices.json`
[source,json]
----
include::{examplesdir}/etc/luids/apiservices.json[]
----

== Configuración de ludns

La configuración del servidor _DNS_ la realizaremos en dos fases. En la primera fase lo pondremos a escuchar en el puerto no estándar `1053` para hacer pruebas y comprobar que funciona correctamente. En la segunda fase, que se verá en el apartado siguiente, haremos los pasos necesarios para ponerlo a escuchar en el puerto estándar.

La configuración es muy sencilla, basta crear el siguiente fichero:

.Contenido temporal `/etc/luids/dns/Corefile`
[source]
----
dnsbl.my-domain.lan:1053 {
  idsapi
  xlistrbl
}

.:1053 {
  cache
  forward . 8.8.8.8 8.8.4.4
}
----

Una vez creado, hay que iniciar el servidor.

[source,bash]
----
sudo systemctl start luids-dns
----

Ahora vamos a llevar a cabo las pruebas del servicio utilizando para ello el comando `dig`.
----
$ dig @localhost +short -p 1053 2.0.0.127.dnsbl.my-domain.lan //<1>
127.0.0.69
$ dig @localhost +short -p 1053 1.0.0.127.dnsbl.my-domain.lan
$ dig @localhost +short -p 1053 www.google.com //<2>
216.58.211.36
----
<1> interrogamos a la lista usando una dirección que debería encontrar
<2> interrogamos al servidor local en puerto `1053` por el dominio `www.google.com` y obtenemos respuesta, lo que indica que el servidor asume el rol de resolvedor.

== Consolidación servicio DNS

Ya tenemos un servidor _DNS_ funcionando pero en un puerto no estándar, así que debemos cambiarlo al puerto que le corresponde. Sin embargo, aquí puede surgir un pequeño problema: puede existir un servidor DNS ya corriendo en dicho puerto.

include::{partialsdir}/disable-local-resolver.adoc[]

Modificaremos la configuración de nuestro servidor DNS con la configuración definitiva.

.Contenido de `/etc/luids/dns/Corefile`
[source]
----
dnsbl.my-domain.lan {
  idsapi
  xlistrbl
}

. {
  cache
  forward . 8.8.8.8 8.8.4.4
}
----

IMPORTANT: Si sólo queremos que responda a la zona y no como resolvedor, deberemos eliminar las tres últimas líneas del fichero `Corefile` del ejemplo y modificar el resolvedor en `/etc/resolv.conf`.

Inicializaremos y habilitaremos el servicio.

[source,bash]
----
sudo systemctl restart luids-ludns.service
sudo systemctl enable luids-ludns.service
----

¡Ya tenemos configurado nuestro servidor DNS con la zona antispam!.

== Configuración del servidor de correo

En primer lugar, el servidor de correo debería ser capaz de resolver la zona creada. Para ello habría dos opciones:

. Usar como resolvedor al servidor DNS recién configurado.
. Configurar la zona padre `my-domain.lan` y delegar la subzona `dnsbl.my-domain.lan` al servidor DNS recién configurado.

IMPORTANT: Conviene proteger con un cortafuegos al servidor DNS para evitar su uso por parte de terceros.

Una vez que el cliente DNS de nuestro servidor de correo está configurado y es capaz de resolver la zona, tan sólo hay que usarla de acuerdo a la configuración.
En el caso de _Postfix_ podría contener algo parecido a esto:

.Posible parte de la configuración de `/etc/postfix/master.cf`
[source]
----
smtpd_recipient_restrictions =
    ....
        reject_rbl_client dnsbl.my-domain.lan,
    ....
----

ifdef::env-site,env-github[]
A continuación: xref:next-steps.adoc[Siguientes pasos]
endif::env-site,env-github[]
