= Introducción
include::{partialsdir}/attributes-es.adoc[]
:guidename: basic-dns-rblzone

== Qué es ^lu^IDS

include::{partialsdir}/what-luids.adoc[]

== ¿Qué es una zona DNS RBL?

Una zona _DNS RBL_ es una zona DNS que sigue la especificación *RFC5782*. Dicha especificación define cómo montar un sistema de listas negras/blancas sobre una infraestructura DNS.

Al tratarse de un estándar, muchos productos de ciberseguridad incluyen la funcionalidad de integrarse con zonas DNS RBL. Entre estos productos tenemos sistemas cortafuegos, servidores proxy, pasarelas de correo, etc.

== ¿Por qué esta configuración?

Una tarea común en los sistemas de correo es comprobar si el servidor que trata de entregar un email para uno de sus destinatarios se encuentra en una lista negra. Para ello, generalmente suelen configurarse los controles en dos fases: la primera fase la realiza el MTA, es decir, el propio software de servidor de correo (por ejemplo _Postfix_). Este chequeo incluye diversas comprobaciones genéricas: si IP tiene resolución inversa, si hay registro SPF, si se hace greylisting, etc.  Además se suelen poner varias zonas DNSxL con información de listas negras. Tras estas comprobaciones, el email pasará a la siguiente fase, en la que otra herramienta más especializada (como puede ser _SpamAssasin_) aplicará diversos filtros más intensivos en recursos (estadísticos, etc) así como cálculos de puntuaciones utilizando un número mayor de lista negras, etc.

En general, suele ser recomendable el uso de listas negras en la primera fase para evitar el consumo de recursos innecesario de la segunda. Sin embargo, las opciones que presenta el MTA para esto suelen ser reducidas.  En el caso de _Postfix_, hasta la llegada de las opciones de chequeo `postscreen` (que se producen antes de que se de cualquier conversación SMTP) y que admite el uso de _thresholds_ (umbrales de respuesta), ni siquiera permitían sistemas de puntuaciones.

== ¿Qué tiene de especial nuestro sistema?

A pesar de las opciones que pueda ofrecernos un sistema como _Postfix_, nunca va a proveer las funcionalidades que puede proporcionar en este aspecto un _servidor xlist_: puntuaciones, chequeos en listas locales y sincronización para consulta "offline", geolocalización, tasas de consulta, gestión de fallos, métricas por lista, estadísticas, etc.

Por todo ello, esta es la propuesta para la presente guía: configurar un servidor _xlistd_ con las listas que utilice nuestro sistema antispam y proporcionarlas mediante un servidor _ludns_ con el plugin _xlistrbl_ que sirva una zona para las consultas del servidor de correo. De esta forma únicamente habrá que configurar una zona en el MTA y el sistema _xlistd_ se encargará del resto. Nótese lo oportuno de esta configuración si tenemos una granja de servidores MTA.

image::why-antispam.svg[why-antispam,width=80%,pdfwidth=80%]

Esta guía se trata de una configuración básica así que no se verán todas las funcionalidades que ofrece nuestro sistema. Sin embargo, conviene que el usuario las conozca por si se anima a continuar explorando más allá de esta guía. Algunas de las funcionalidades adicionales son:

* ofrece soporte de nombres de dominio e ipv6,
* es posible usar listas negras online y sincronizarlas,
* es posible alojar múltiples zonas utilizando a su vez diferentes servidores _xlistd_,
* es posible reutilizar las listas y dar servicio a múltiples servidores _DNS_,
* provee de instrumentación para su integración en un sistema de monitorización _Prometheus_ y así tener información en "tiempo real",
* disponible en _Docker_ y con algunas características que lo hace ideal para su despliegue en entornos Cloud con herramientas como _Kubernetes_.

Así que una vez visto qué es y qué ventajas aporta nuestro software sobre otros, pongámonos manos a la obra.

ifdef::env-site,env-github[]
A continuación: xref:design.adoc[Diseño del sistema]
endif::env-site,env-github[]
